### ISSUE TITLE
broken link in the documentation

### ISSUE THREAD

**Issue by zapashcanon** [CatalaLang/catala#504] opened 2023-09-09 18:56 UTC
Hi,

[Here](https://catala-lang.org/ocaml_docs/catala/plugins.html), the `Driver.Plugin` link, after:

> See the following module for the registration interface:

Is broken (the home page is displayed somehow).

EDIT: same [here](https://catala-lang.org/ocaml_docs/catala/Driver/) when clicking on the `Plugin.PluginAPI` link.

**Comment by denismerigoux** [comment] 2023-09-19 10:18
Weird, I can't reproduce by doing `make doc` on my machine and inspecting the generated HTML. @AltGr ?

**Comment by AltGr** [comment] 2023-10-06 08:47
Should be fixed by https://github.com/CatalaLang/catala-website/pull/57 which redirects the whole doc to the nightly CI-generated https://catalalang.github.io/catala/api-doc/

**Closed** 2024-06-26 08:13 UTC
Labels: ❌ bug, 👌 good first issue, 👪 help wanted, 🏗️ build system
