### ISSUE TITLE
Poor error reporting if the language is wrong

### ISSUE THREAD

**Issue by msprotz** [CatalaLang/catala#148] opened 2021-09-28 21:51 UTC
The default locale of Catala seems to be French, meaning that if I forget to specify `--language=en`, my file does not parse. This is fine, but the parser suggests *English* keywords, and gives out an error message in English, so this is quite confusing. 

```
jonathan@absinthe:/tmp $ catala OCaml !$
catala OCaml test.catala_en
[ERROR] Syntax error at token "declaration"
[ERROR] Message: expected a declaration or a scope use
[ERROR] Autosuggestion: did you mean "new", or maybe "scope"?
[ERROR] 
[ERROR] Error token:
[ERROR]  --> test.catala_en
[ERROR]   | 
[ERROR] 6 | declaration scope Foo:
[ERROR]   | ^^^^^^^^^^^
[ERROR]   + 
[ERROR] 
[ERROR] Last good token:
[ERROR]  --> test.catala_en
[ERROR]   | 
[ERROR] 5 | ```catala
[ERROR]   | ^^^^^^^^^
[ERROR]   + 
```

Suggestion #1: if catala is set to parse in French, error messages ought to be in French, and suggested tokens need to be in French too

Suggestion #2: switch default to English to better reach a global audience

**Comment by denismerigoux** [comment] 2021-09-29 07:24
There is no default locale anymore in Catala, you seem to be using an old version of the compiler : 

https://github.com/CatalaLang/catala/blob/8c7d538cfbae1efcb7e978147ef0d022890dc73c/compiler/driver.ml#L41-L60

Instead, the locale is inferred from the file extension. Previsously, there used to be a default locale and it was not French but an "abbreviated" English syntax that Nicolas designed during his internship, and that I decided to discontinue later because its usefulness was limited.

**Comment by denismerigoux** [comment] 2021-11-06 21:30
Closing, the problem was that @msprotz was using an old version of the compiler.

**Closed by denismerigoux** 2021-11-06 21:30 UTC
Labels: ❓ invalid, 💬 discussion
