### ISSUE TITLE
List concatenation operator

### ISSUE THREAD

**Issue by msprotz** [CatalaLang/catala#301] opened 2022-08-01 18:29 UTC
It would be convenient to have a list concatenation operator. The infix, right-associative operator `@` like in OCaml could be used, or `++` like in Haskell would work as well.

**Comment by denismerigoux** [comment] 2022-08-09 13:02
I'm actually in favor of `++`. Will implement it today.

**Comment by denismerigoux** [comment] 2022-08-09 13:04
Wait, duplicate of #109 and already fixed by #137. Just use `++` :)

**Closed by denismerigoux** 2022-08-09 13:04 UTC
Labels: ✨ enhancement, 👌 good first issue, 🔧 compiler, 💡 language

**Comment by msprotz** [comment] 2022-08-09 15:55
Thanks Denis!
